// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwu-WnKDBzKEGSAM8LOFzVQpaKEIbB-WI',
    appId: '1:709370489781:web:15c15fdf7f41b9fd2687fc',
    messagingSenderId: '709370489781',
    projectId: 'flash-card-22d3c',
    authDomain: 'flash-card-22d3c.firebaseapp.com',
    storageBucket: 'flash-card-22d3c.firebasestorage.app',
    measurementId: 'G-5NTNZXT6E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGR8iQ2ZwgF7RnE5QpF-OJnJv8PHkGXQs',
    appId: '1:709370489781:android:0ee6a8a5c3a9efca2687fc',
    messagingSenderId: '709370489781',
    projectId: 'flash-card-22d3c',
    storageBucket: 'flash-card-22d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY7-Y7tQCMH0pZmHd6H9J8n4OJ9QXvN4I',
    appId: '1:709370489781:ios:0ee6a8a5c3a9efca2687fc',
    messagingSenderId: '709370489781',
    projectId: 'flash-card-22d3c',
    storageBucket: 'flash-card-22d3c.firebasestorage.app',
    iosBundleId: 'com.example.vocablearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY7-Y7tQCMH0pZmHd6H9J8n4OJ9QXvN4I',
    appId: '1:709370489781:ios:0ee6a8a5c3a9efca2687fc',
    messagingSenderId: '709370489781',
    projectId: 'flash-card-22d3c',
    storageBucket: 'flash-card-22d3c.firebasestorage.app',
    iosBundleId: 'com.example.vocablearner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwu-WnKDBzKEGSAM8LOFzVQpaKEIbB-WI',
    appId: '1:709370489781:web:15c15fdf7f41b9fd2687fc',
    messagingSenderId: '709370489781',
    projectId: 'flash-card-22d3c',
    authDomain: 'flash-card-22d3c.firebaseapp.com',
    storageBucket: 'flash-card-22d3c.firebasestorage.app',
    measurementId: 'G-5NTNZXT6E7',
  );
}
